### ISSUE TITLE
Will this work for Mac Catalyst to create system menu

### ISSUE THREAD

**Issue by elmcapp** [hexedbits/StatusItemController#44]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

Will this work for Mac Catalyst to create system menu. Also can we refresh the menu in a way to have dynamic menu

### Problem

I need to create system menu for Mac Catalyst

### Proposed Solution

*

### Alternatives Considered

*

**Comment by jessesquires** [comment]
Hey @elmcapp !

I have not used Mac Catalyst, so I'm not sure if this is compatible or not.
